## Exercises: Modify the dataset

In [1]:
import pandas as pd
employees = pd.read_json("../Data/employees.json")

**Current state of the "employees" dataset**

Rerun the code block below after each modification you do, to see its current state.

In [2]:
employees

first_name last_name              job_title  salary       department
0       John       Doe         Sales Director  120000            Sales
1       Jane     Smith         HR Coordinator   60000  Human Resources
2    Michael   Johnson      Software Engineer  110000               IT
3      Sarah  Williams   Marketing Specialist   75000            Sales
4      David     Brown             HR Manager   90000  Human Resources
5      Emily     Davis  IT Support Specialist   55000               IT
6      Jacob    Wilson   Sales Representative   80000            Sales
7     Olivia     Moore      Marketing Manager  100000            Sales
8      Ethan       Lee      Financial Analyst   85000            Sales
9     Sophia    Taylor           HR Assistant   50000  Human Resources

**Do the following operations on the "employees" dataset:**

**OP1:** Create a new column "name" which contains the full name (eg. "John Doe") for each employee.

<details>
<summary>Result</summary>
<br>
&nbsp;&nbsp;&nbsp;<b>name</b><br>
&nbsp;&nbsp;&nbsp;John Doe<br>
&nbsp;&nbsp;&nbsp;Jane Smith<br>
&nbsp;&nbsp;&nbsp;Michael Johnson<br>
&nbsp;&nbsp;&nbsp;...<br>
</details>

In [5]:
employees["name"] = employees["first_name"] + " " + employees["last_name"]
employees

first_name last_name              job_title  salary       department  \
0       John       Doe         Sales Director  120000            Sales   
1       Jane     Smith         HR Coordinator   60000  Human Resources   
2    Michael   Johnson      Software Engineer  110000               IT   
3      Sarah  Williams   Marketing Specialist   75000            Sales   
4      David     Brown             HR Manager   90000  Human Resources   
5      Emily     Davis  IT Support Specialist   55000               IT   
6      Jacob    Wilson   Sales Representative   80000            Sales   
7     Olivia     Moore      Marketing Manager  100000            Sales   
8      Ethan       Lee      Financial Analyst   85000            Sales   
9     Sophia    Taylor           HR Assistant   50000  Human Resources   

              name  
0         John Doe  
1       Jane Smith  
2  Michael Johnson  
3   Sarah Williams  
4      David Brown  
5      Emily Davis  
6     Jacob Wilson  
7     Olivia Moore  
8        Ethan Lee  
9    Sophia Taylor

<div style="display: inline">
<b>OP2:</b> Create a new column "email" with the following format: firstname.lastname@mockcompany.com
</div><br>

*Note: email addresses should be all lower case.*

<details>
<summary>Result</summary>
<br>
&nbsp;&nbsp;&nbsp;<b>email</b><br>
&nbsp;&nbsp;&nbsp;john.doe@mockcompany.com<br>
&nbsp;&nbsp;&nbsp;jane.smith@mockcompany.com<br>
&nbsp;&nbsp;&nbsp;michael.johnson@mockcompany.com<br>
&nbsp;&nbsp;&nbsp;...<br>
</details>

In [10]:
employees["email"] = employees["first_name"] + employees["last_name"] + "@mockcompany.com"
employees["email"] = [str(employee).lower() for employee in employees["email"]]
employees

first_name last_name              job_title  salary       department  \
0       John       Doe         Sales Director  120000            Sales   
1       Jane     Smith         HR Coordinator   60000  Human Resources   
2    Michael   Johnson      Software Engineer  110000               IT   
3      Sarah  Williams   Marketing Specialist   75000            Sales   
4      David     Brown             HR Manager   90000  Human Resources   
5      Emily     Davis  IT Support Specialist   55000               IT   
6      Jacob    Wilson   Sales Representative   80000            Sales   
7     Olivia     Moore      Marketing Manager  100000            Sales   
8      Ethan       Lee      Financial Analyst   85000            Sales   
9     Sophia    Taylor           HR Assistant   50000  Human Resources   

              name                           email  
0         John Doe         johndoe@mockcompany.com  
1       Jane Smith       janesmith@mockcompany.com  
2  Michael Johnson  michaeljohnson@mockcompany.com  
3   Sarah Williams   sarahwilliams@mockcompany.com  
4      David Brown      davidbrown@mockcompany.com  
5      Emily Davis      emilydavis@mockcompany.com  
6     Jacob Wilson     jacobwilson@mockcompany.com  
7     Olivia Moore     oliviamoore@mockcompany.com  
8        Ethan Lee        ethanlee@mockcompany.com  
9    Sophia Taylor    sophiataylor@mockcompany.com

**OP3:** Remove the columns "first_name" and "last_name", and put the columns "name" and "email" first.
<details>
<summary>Result</summary>
<br>
&nbsp;&nbsp;&nbsp;<b>name&nbsp;&nbsp;&nbsp;email&nbsp;&nbsp;&nbsp;job_title&nbsp;&nbsp;&nbsp;salary&nbsp;&nbsp;&nbsp;department</b>
</details>

In [19]:
# Get the column names and values of the last two columns
new_column_names = ['name', 'email']
new_column_values = employees[new_column_names].copy()

# Remove the last two columns
employees.drop(columns=new_column_names, inplace=True)

# Insert the values with new column names at the beginning
employees.insert(0, new_column_names[0], new_column_values[new_column_names[0]])
employees.insert(1, new_column_names[1], new_column_values[new_column_names[1]])


employees

name                           email       first_name  \
0         John Doe         johndoe@mockcompany.com         John Doe   
1       Jane Smith       janesmith@mockcompany.com       Jane Smith   
2  Michael Johnson  michaeljohnson@mockcompany.com  Michael Johnson   
3   Sarah Williams   sarahwilliams@mockcompany.com   Sarah Williams   
4      David Brown      davidbrown@mockcompany.com      David Brown   
5      Emily Davis      emilydavis@mockcompany.com      Emily Davis   
6     Jacob Wilson     jacobwilson@mockcompany.com     Jacob Wilson   
7     Olivia Moore     oliviamoore@mockcompany.com     Olivia Moore   
8        Ethan Lee        ethanlee@mockcompany.com        Ethan Lee   
9    Sophia Taylor    sophiataylor@mockcompany.com    Sophia Taylor   

                        last_name              job_title  salary  \
0         johndoe@mockcompany.com         Sales Director  120000   
1       janesmith@mockcompany.com         HR Coordinator   60000   
2  michaeljohnson@mockcompany.com      Software Engineer  110000   
3   sarahwilliams@mockcompany.com   Marketing Specialist   75000   
4      davidbrown@mockcompany.com             HR Manager   90000   
5      emilydavis@mockcompany.com  IT Support Specialist   55000   
6     jacobwilson@mockcompany.com   Sales Representative   80000   
7     oliviamoore@mockcompany.com      Marketing Manager  100000   
8        ethanlee@mockcompany.com      Financial Analyst   85000   
9    sophiataylor@mockcompany.com           HR Assistant   50000   

        department  
0            Sales  
1  Human Resources  
2               IT  
3            Sales  
4  Human Resources  
5               IT  
6            Sales  
7            Sales  
8            Sales  
9  Human Resources

In [20]:
employees.drop(columns=["first_name", "last_name"], inplace=True)
employees

name                           email              job_title  \
0         John Doe         johndoe@mockcompany.com         Sales Director   
1       Jane Smith       janesmith@mockcompany.com         HR Coordinator   
2  Michael Johnson  michaeljohnson@mockcompany.com      Software Engineer   
3   Sarah Williams   sarahwilliams@mockcompany.com   Marketing Specialist   
4      David Brown      davidbrown@mockcompany.com             HR Manager   
5      Emily Davis      emilydavis@mockcompany.com  IT Support Specialist   
6     Jacob Wilson     jacobwilson@mockcompany.com   Sales Representative   
7     Olivia Moore     oliviamoore@mockcompany.com      Marketing Manager   
8        Ethan Lee        ethanlee@mockcompany.com      Financial Analyst   
9    Sophia Taylor    sophiataylor@mockcompany.com           HR Assistant   

   salary       department  
0  120000            Sales  
1   60000  Human Resources  
2  110000               IT  
3   75000            Sales  
4   90000  Human Resources  
5   55000               IT  
6   80000            Sales  
7  100000            Sales  
8   85000            Sales  
9   50000  Human Resources

**OP4:** Update column titles to make the first letter in each title upper case. Also replace the underscore character in "job_title" with a space.
<details>
<summary>Result</summary>
<br>
&nbsp;&nbsp;&nbsp;<b>Name&nbsp;&nbsp;&nbsp;Email&nbsp;&nbsp;&nbsp;Job title&nbsp;&nbsp;&nbsp;Salary&nbsp;&nbsp;&nbsp;Department</b>
</details>

In [23]:
employees.columns = employees.columns.str.title()
employees.columns = employees.columns.str.replace("_"," ")
employees

Name                           Email              Job Title  \
0         John Doe         johndoe@mockcompany.com         Sales Director   
1       Jane Smith       janesmith@mockcompany.com         HR Coordinator   
2  Michael Johnson  michaeljohnson@mockcompany.com      Software Engineer   
3   Sarah Williams   sarahwilliams@mockcompany.com   Marketing Specialist   
4      David Brown      davidbrown@mockcompany.com             HR Manager   
5      Emily Davis      emilydavis@mockcompany.com  IT Support Specialist   
6     Jacob Wilson     jacobwilson@mockcompany.com   Sales Representative   
7     Olivia Moore     oliviamoore@mockcompany.com      Marketing Manager   
8        Ethan Lee        ethanlee@mockcompany.com      Financial Analyst   
9    Sophia Taylor    sophiataylor@mockcompany.com           HR Assistant   

   Salary       Department  
0  120000            Sales  
1   60000  Human Resources  
2  110000               IT  
3   75000            Sales  
4   90000  Human Resources  
5   55000               IT  
6   80000            Sales  
7  100000            Sales  
8   85000            Sales  
9   50000  Human Resources

**OP5:** Change the data type of column "Salary" to float64.
<details>
<summary>Result</summary>
<br>
&nbsp;&nbsp;&nbsp;Salary: int64 => float64
</details>

In [24]:
employees["Salary"] = [float(val) for val in employees["Salary"]]

**OP6:** The company decided to give everyone in sales a 10% salary increase. Update the dataset accordingly.

<details>
<summary>Result</summary>
<br>
&nbsp;&nbsp;&nbsp;John Doe&nbsp;&nbsp;&nbsp;132000.0<br>
&nbsp;&nbsp;&nbsp;Jane Smith&nbsp;&nbsp;&nbsp;60000.0<br>
&nbsp;&nbsp;&nbsp;Michael Johnson&nbsp;&nbsp;&nbsp;110000.0	<br>
&nbsp;&nbsp;&nbsp;Sarah Williams&nbsp;&nbsp;&nbsp;82500.0<br>
&nbsp;&nbsp;&nbsp;...<br>
</details>

In [29]:
for i, val in enumerate(employees["Department"]):
    employees["Salary"][i] = employees["Salary"][i] * 1.1 if employees["Department"][i] == "Sales" else employees["Salary"][i]
employees

C:\Users\Mikae\AppData\Local\Temp\ipykernel_21860\3050847348.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  employees["Salary"][i] = employees["Salary"][i] * 1.1 if employees["Department"][i] == "Sales" else employees["Salary"][i]
C:\Users\Mikae\AppData\Local\Temp\ipykernel_21860\3050847348.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  employees["Salary"][i] = employees["Salary"][i] * 1.1 if employees["Department"][i] == "Sales" else employees["Salary"][i]
C:\Users\Mikae\AppData\Local\Temp\ipykernel_21860\3050847348.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFr

Name                           Email              Job Title  \
0         John Doe         johndoe@mockcompany.com         Sales Director   
1       Jane Smith       janesmith@mockcompany.com         HR Coordinator   
2  Michael Johnson  michaeljohnson@mockcompany.com      Software Engineer   
3   Sarah Williams   sarahwilliams@mockcompany.com   Marketing Specialist   
4      David Brown      davidbrown@mockcompany.com             HR Manager   
5      Emily Davis      emilydavis@mockcompany.com  IT Support Specialist   
6     Jacob Wilson     jacobwilson@mockcompany.com   Sales Representative   
7     Olivia Moore     oliviamoore@mockcompany.com      Marketing Manager   
8        Ethan Lee        ethanlee@mockcompany.com      Financial Analyst   
9    Sophia Taylor    sophiataylor@mockcompany.com           HR Assistant   

     Salary       Department  
0  132000.0            Sales  
1   60000.0  Human Resources  
2  110000.0               IT  
3   82500.0            Sales  
4   90000.0  Human Resources  
5   55000.0               IT  
6   88000.0            Sales  
7  110000.0            Sales  
8   93500.0            Sales  
9   50000.0  Human Resources

**OP7:** The company hired a new software engineer. Add a new row with appropriate values to the dataset.
<details>
<summary>Result</summary>
<br>
<b>Example:</b><br>
&nbsp;&nbsp;&nbsp;<b>Name:</b> Jennifer Lee<br>
&nbsp;&nbsp;&nbsp;<b>Email:</b> jennifer.lee@mockcompany.com<br>
&nbsp;&nbsp;&nbsp;<b>Job title:</b> Software Engineer<br>
&nbsp;&nbsp;&nbsp;<b>Salary:</b> 100.000<br>
&nbsp;&nbsp;&nbsp;<b>Department:</b> IT<br>
</details>

In [32]:
new_row = {'Name': 'Carl Young', 'Email': 'carlyoung@mockcompany.com', 'Job Title': 'Software Engineer', "Salary": 10000, 'Department': "IT"}

# Use the loc method to add the new row
employees.loc[employees.index.max() + 1] = new_row
employees

Name                           Email              Job Title  \
0          John Doe         johndoe@mockcompany.com         Sales Director   
1        Jane Smith       janesmith@mockcompany.com         HR Coordinator   
2   Michael Johnson  michaeljohnson@mockcompany.com      Software Engineer   
3    Sarah Williams   sarahwilliams@mockcompany.com   Marketing Specialist   
4       David Brown      davidbrown@mockcompany.com             HR Manager   
5       Emily Davis      emilydavis@mockcompany.com  IT Support Specialist   
6      Jacob Wilson     jacobwilson@mockcompany.com   Sales Representative   
7      Olivia Moore     oliviamoore@mockcompany.com      Marketing Manager   
8         Ethan Lee        ethanlee@mockcompany.com      Financial Analyst   
9     Sophia Taylor    sophiataylor@mockcompany.com           HR Assistant   
10       Carl Young       carlyoung@mockcompany.com      Software Engineer   

      Salary       Department  
0   132000.0            Sales  
1    60000.0  Human Resources  
2   110000.0               IT  
3    82500.0            Sales  
4    90000.0  Human Resources  
5    55000.0               IT  
6    88000.0            Sales  
7   110000.0            Sales  
8    93500.0            Sales  
9    50000.0  Human Resources  
10   10000.0               IT

**OP8:** The company decided to hire a lot of new software engineers.

Create python code that asks the user to input the name and salary of the new software engineer, and then automatically adds the new employee to the dataset. Also, ensure that each employee get a unique index in the dataset.

<details>
<summary>Result</summary>
<br>
<b>Example:</b><br>
&nbsp;&nbsp;&nbsp;Input name of new software engineer: Daniel Brown<br>
&nbsp;&nbsp;&nbsp;Input the salary for Daniel Brown: 95.000<br>
<br>
&nbsp;&nbsp;&nbsp;<b>Name:</b> Daniel Brown<br>
&nbsp;&nbsp;&nbsp;<b>Email:</b> daniel.brown@mockcompany.com<br>
&nbsp;&nbsp;&nbsp;<b>Job title:</b> Software Engineer<br>
&nbsp;&nbsp;&nbsp;<b>Salary:</b> 95.000<br>
&nbsp;&nbsp;&nbsp;<b>Department:</b> IT<br>
</details>

In [39]:
def new_engineer(name:str, salary:float):
    email = name.lower().strip().replace(" ","") + "@mockcompany.com"

    new_row = {
        'Name': name.strip(), 
        'Email': email, 
        'Job Title': 'Software Engineer', 
        "Salary": salary,
        'Department': "IT",
    }
    return new_row

print("Add new Software Engineer.\nEnter emptry string instead of name to exit.")
print("============================================================================\n")

while True:
    try:
        name = input("Enter name: ").strip()
        if name == "":
            break
    except ValueError:
        print("Something peculiar just happened...")
    try:
        salary = float(input("Enter salary: ").strip())
        break
    except:
        print("Enter salary in integer digit form.")

if name != "":
    employees.loc[employees.index.max() + 1] = new_engineer(name,salary)

Add new Software Engineer.
Enter emptry string instead of name to exit.



In [40]:
employees

Name                           Email              Job Title  \
0          John Doe         johndoe@mockcompany.com         Sales Director   
1        Jane Smith       janesmith@mockcompany.com         HR Coordinator   
2   Michael Johnson  michaeljohnson@mockcompany.com      Software Engineer   
3    Sarah Williams   sarahwilliams@mockcompany.com   Marketing Specialist   
4       David Brown      davidbrown@mockcompany.com             HR Manager   
5       Emily Davis      emilydavis@mockcompany.com  IT Support Specialist   
6      Jacob Wilson     jacobwilson@mockcompany.com   Sales Representative   
8         Ethan Lee        ethanlee@mockcompany.com      Financial Analyst   
9     Sophia Taylor    sophiataylor@mockcompany.com           HR Assistant   
10       Carl Young       carlyoung@mockcompany.com      Software Engineer   
11      Lisa lowrey      lisalowrey@mockcompany.com      Software Engineer   
12     Olivia Moore     oliviamoore@mockcompany.com      Software Engineer   

      Salary       Department  
0   132000.0            Sales  
1    60000.0  Human Resources  
2   110000.0               IT  
3    82500.0            Sales  
4    90000.0  Human Resources  
5    55000.0               IT  
6    88000.0            Sales  
8    93500.0            Sales  
9    50000.0  Human Resources  
10   10000.0               IT  
11   10000.0               IT  
12    4000.0               IT

**OP9:** Olivia Moore quits her job. Remove her data from the dataset.

In [38]:
employees=employees.drop(employees[employees['Name'] == "Olivia Moore"].index[0])
employees

Name                           Email              Job Title  \
0          John Doe         johndoe@mockcompany.com         Sales Director   
1        Jane Smith       janesmith@mockcompany.com         HR Coordinator   
2   Michael Johnson  michaeljohnson@mockcompany.com      Software Engineer   
3    Sarah Williams   sarahwilliams@mockcompany.com   Marketing Specialist   
4       David Brown      davidbrown@mockcompany.com             HR Manager   
5       Emily Davis      emilydavis@mockcompany.com  IT Support Specialist   
6      Jacob Wilson     jacobwilson@mockcompany.com   Sales Representative   
8         Ethan Lee        ethanlee@mockcompany.com      Financial Analyst   
9     Sophia Taylor    sophiataylor@mockcompany.com           HR Assistant   
10       Carl Young       carlyoung@mockcompany.com      Software Engineer   
11      Lisa lowrey      lisalowrey@mockcompany.com      Software Engineer   

      Salary       Department  
0   132000.0            Sales  
1    60000.0  Human Resources  
2   110000.0               IT  
3    82500.0            Sales  
4    90000.0  Human Resources  
5    55000.0               IT  
6    88000.0            Sales  
8    93500.0            Sales  
9    50000.0  Human Resources  
10   10000.0               IT  
11   10000.0               IT

**OP10**: Make sure that the python script in *OP8* still gives a unique index to each new employee, even after removing rows.

### Final note:
Just to be clear, a real company would most likely store their employee data in a database, and loading them into a pandas dataframe to do these kind of operations wouldn't make much sense. The above examples are purely for learning the different operations of pandas.